FROM ruby:2.5.0
ENV RAILS_ENV production bundle exec assets:precompile
ENV RACK_ENV production
ENV RAILS_LOG_TO_STDOUT true
ENV RAILS_SERVE_STATIC_FILES true
ENV ADMIN_EMAIL administrator@tdt4242.shop
ENV ADMIN_PASSWORD administrator
ENV DOMAIN_NAME tdt4242eshop.azurewebsites.net
ENV SECRET_KEY_BASE c6af7b3b873e6c184d39d4be9b568ef963e8dd001f1020f75d1788f468705c4c7f3dc9241387048dff06331ad78ddf7ec757c49142dd619e4d304648feb6a335
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ADD Gemfile /usr/src/app/Gemfile
ADD Gemfile.lock /usr/src/app/Gemfile.lock
RUN bundle install
ADD . /usr/src/app
COPY config/database.yml /usr/src/app/config/database.yml
RUN rake db:setup
EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
